// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVVA2ly-ykITuKNy6PTQPHIjfjLtuBif8',
    appId: '1:901491020290:web:e18315f999a24e1a424d1b',
    messagingSenderId: '901491020290',
    projectId: 'iot-hydrogrow',
    authDomain: 'iot-hydrogrow.firebaseapp.com',
    databaseURL: 'https://iot-hydrogrow-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iot-hydrogrow.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1vYoS-Kw8M_rJU9wAoTxkIQ5pRqHRG5c',
    appId: '1:901491020290:android:abdaa5011a0159ff424d1b',
    messagingSenderId: '901491020290',
    projectId: 'iot-hydrogrow',
    databaseURL: 'https://iot-hydrogrow-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iot-hydrogrow.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJ-cwwVM4Yie6KQe3MzxoQotF1rABH2Tk',
    appId: '1:901491020290:ios:5ed606aa1465008c424d1b',
    messagingSenderId: '901491020290',
    projectId: 'iot-hydrogrow',
    databaseURL: 'https://iot-hydrogrow-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iot-hydrogrow.firebasestorage.app',
    iosBundleId: 'com.example.iotHydrogrow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJ-cwwVM4Yie6KQe3MzxoQotF1rABH2Tk',
    appId: '1:901491020290:ios:5ed606aa1465008c424d1b',
    messagingSenderId: '901491020290',
    projectId: 'iot-hydrogrow',
    databaseURL: 'https://iot-hydrogrow-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iot-hydrogrow.firebasestorage.app',
    iosBundleId: 'com.example.iotHydrogrow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVVA2ly-ykITuKNy6PTQPHIjfjLtuBif8',
    appId: '1:901491020290:web:fe33fa11dc9c0db3424d1b',
    messagingSenderId: '901491020290',
    projectId: 'iot-hydrogrow',
    authDomain: 'iot-hydrogrow.firebaseapp.com',
    databaseURL: 'https://iot-hydrogrow-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iot-hydrogrow.firebasestorage.app',
  );

}
